name: Publish to Crates.io

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "New version (e.g., 1.1.0)"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust & Cargo Tools
        run: |
          rustup update stable
          cargo install cargo-edit

      - name: Bump Version in Cargo.toml
        run: cargo set-version ${{ github.event.inputs.new_version }}

      - name: Commit & Push Version Bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Bump version to ${{ github.event.inputs.new_version }}"
          git push

      - name: Publish to Crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}